canonical/charming-actions

.github/workflows/integrate.yaml, README.md, action.yaml, dist/index.js, main.js, test-bundle/README.md, test-bundle/bundle.yaml, test-bundle/charmcraft.yaml, test-charm/metadata.yaml
Allows for publishing a bundle as well as a charm. Presents `bundle-path` option that can be set instead of `charm-path`.
=> Add bundle publishing

.eslintrc.yml, .github/workflows/integrate.yaml, dist/channel/index.js, dist/check-libraries/index.js, dist/upload-bundle/index.js, dist/upload-charm/index.js, package-lock.json, src/services/charmcraft/charmcraft.test.ts, src/services/charmcraft/charmcraft.ts
Fixes `charmcraft upload` falling when `upload-image: false` because the resulting flag that specifies the resource name and revision is empty.
Although we are not updating the `oci-image` when `upload-image: false`, we still need to attach an existing image revision to the charm with the flag at the end (i.e. `--resource=<charm-oci-image-name>:<revision number>`)
`charmcraft upload` command before the fix:
- `upload-resource: false`: `/snap/bin/charmcraft upload --quiet --release latest/edge /home/runner/work/test-edge-release/test-edge-release/edge-release-test-charm_ubuntu-20.04-amd64.charm`
After the fix:
- `upload-resource: false`: `/snap/bin/charmcraft upload --quiet --release latest/edge /home/runner/work/test-edge-release/test-edge-release/edge-release-test-charm_ubuntu-20.04-amd64 …
=> Fix: fails when upload-image:false

dist/channel/index.js, dist/check-libraries/index.js, dist/upload-bundle/index.js, dist/upload-charm/index.js, src/services/charmcraft/charmcraft.ts
If a charm has dependencies that would have to be installed through ``apt-get`` (defined in ``charmcraft.yaml``, under build-packages), the ``upload-charm`` action fails because it tries to build charm and install these dependencies without the necessary privileges.
Fixes: https://github.com/canonical/charming-actions/issues/34
=> Sets charmcraft pack as root

upload-bundle/README.md
It should be ``canonical/charming-actions/upload-bundle``, not ``canonical/charming-actions/upload-charm``.
=> Fixes typo in the upload-bundle README

dist/channel/index.js, dist/check-libraries/index.js, dist/release-charm/index.js, dist/upload-bundle/index.js, dist/upload-charm/index.js, package.json, release-charm/README.md, release-charm/action.yaml, src/actions/release-charm/release-charm.ts, src/services/charmcraft/charmcraft.test.ts, src/services/charmcraft/charmcraft.ts, src/services/charmcraft/types.ts, src/types.ts
This is a first draft at using `charmcraft status`'s formatted output for the `release-charm` action in order to handle releasing charms that have charmhub branches (see #45 for details on the issue).
This is not the best javascript, but instead a quick hack to get something working.
fixes #45
=> feat: use `charmcraft` structured status output for `release-charm`

src/actions/check-libraries/check-libraries.ts
charmcraft fetch-libs is not a charmcraft command, changing the messaging with the correct command to avoid issues.
=> fix: fix charmcraft command when check-lib fails

dist/channel/index.js, dist/check-libraries/index.js, dist/release-charm/index.js, dist/upload-bundle/index.js, dist/upload-charm/index.js, src/services/charmcraft/charmcraft.test.ts, src/services/charmcraft/charmcraft.ts, src/services/docker/docker.test.ts, src/services/docker/docker.ts, src/services/docker/index.ts
This change adds a step of extracting an image's digest from
docker and then calling `charmcraft upload-resource`
with that digest rather than the image name.
This conforms with charmcraft's expected usage:
https://discourse.charmhub.io/t/charmcrafts-upload-resource-command/4580
Fixes #67
[This action run](https://github.com/canonical/kubeflow-profiles-operator/actions/runs/3236847794/jobs/5305642876) from kubeflow-profiles-operator gives an example of this action working (CI is pinned to this PR's branch).  Previous to this PR, [the action would fail](https://github.com/canonical/kubeflow-profiles-operator/actions/runs/3236834548/jobs/5303166564).
=> fix: upload resources using digest in upload-charm

dist/channel/index.js, dist/check-libraries/index.js, dist/release-charm/index.js, dist/upload-bundle/index.js, dist/upload-charm/index.js, src/services/docker/docker.test.ts, src/services/docker/docker.ts
`docker image ls imagename` expects `imagename` to exclude the repository
if it is from `docker.io/`, but include the repository otherwise.
Previously, `getImageDigest` incorrectly always stripped the repository
from the imagename.
For example:
```
docker pull docker.io/alpine:latest
docker image ls alpine
```
will show images with Repository=alpine, NOT docker.io/alpine, and
```
docker image ls docker.io/alpine
```
returns an empty list.  But,
```
docker pull quay.io/helix-ml/mlflow
docker image ls helix-ml/mlflow
docker image ls mlflow
```
returns empty lists, while
```
docker image ls quay.io/helix-ml/mlflow
```
returns the expected image.
=> fix: handle image names with repository in upload-charm

dist/channel/index.js, dist/check-libraries/index.js, dist/release-charm/index.js, dist/upload-bundle/index.js, dist/upload-charm/index.js, src/services/artifact/artifact.ts
In some cases we're running charmcraft commands with `sudo` and in others not, so make sure we're gathering logs in both cases. See https://github.com/canonical/nginx-ingress-integrator-operator/actions/runs/3445054467/jobs/5775634047 for an example of what this might miss.
This may need careful review of this as this is my first contribution to this project and I'm not very familiar with the tooling around npm.
=> Gather logs from sudo and non-sudo invocation of charmcraft

dist/channel/index.js, dist/check-libraries/index.js, dist/release-charm/index.js, dist/upload-bundle/index.js, dist/upload-charm/index.js, dist/upload/index.js, src/services/charmcraft/charmcraft.ts
When you use charming-actions, you can get a warning that reads `No resources where uploaded as part of this build` and it should be `were uploaded`. This PR fixes this.
=> fix(message): Replace where with were in warnings

dist/channel/index.js, dist/check-libraries/index.js, dist/release-charm/index.js, dist/release-libraries/index.js, dist/upload-bundle/index.js, dist/upload-charm/index.js, src/actions/upload-charm/upload-charm.ts, src/services/charmcraft/charmcraft.ts, upload-charm/action.yaml
As requested by @taurus-forever and team. The default is, intentionally, to keep it enabled as that is what most users will likely want currently.
(No need to review the dist files as they are generated on push. 😅)
closes #80.
=> add flag to disable destructive mode

upload-charm/README.md
Otherwise GH action doesn't work:
`Warning: Unexpected input(s) 'destructive', valid inputs are ['destructive-mode', 'channel', 'tag-prefix', 'charm-path', 'charmcraft-channel', 'upload-image', 'credentials', 'github-token', 'resource-overrides']`
=> Fix destructive-mode option in README

check-libraries/action.yaml, package-lock.json, package.json
Currently, this action triggers a deprecation warning on every run. I'm naively changing this to test if it works!
Fixes #83
=> build: use node16 for `check-libraries`

README.md, dist/channel/index.js, dist/check-libraries/index.js, dist/release-charm/index.js, dist/release-libraries/index.js, dist/upload-bundle/index.js, dist/upload-charm/index.js, src/actions/upload-charm/upload-charm.ts, src/services/charmcraft/charmcraft.test.ts, src/services/charmcraft/charmcraft.ts, upload-charm/README.md, upload-charm/action.yaml
This PR introduces the option to build a charm before passing it over to the `upload-charm` action. This is especially useful when one wants to test a charm before uploading it. The current state of the `upload-charm` action forces charm authors to re-build the charm after being tested, meaning that it's possible that the tested charm is not exactly the same as the one that was tested.
```yaml
name: Release
on:
push:
branches:
- main
jobs:
build:
name: Release
runs-on: ubuntu-latest
steps:
- name: Checkout
uses: actions/checkout@v3
- name: Select charmhub channel
uses: canonical/charming-actions/channel@2.2.6
id: channel
- name: Fetch Tested Charm
uses: actions/download-artifact@v3
with:
name: tested-charm
- name: Move charm in current directory
run: find ./ -name my-precious.charm -exec …
```
=> Adds support for pre-built charms in the `upload-charm` action

channel/action.yaml, release-charm/action.yaml, upload-bundle/action.yaml, upload-charm/action.yaml
GitHub mentions that Node.js 12 actions are deprecated; this PR updates the node version to fix the issue.
```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: canonical/charming-actions/check-libraries@2.2.0. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```
=> update to node16 for deprecation warnings

dist/channel/index.js, dist/check-libraries/index.js, dist/release-charm/index.js, dist/release-libraries/index.js, dist/upload-bundle/index.js, dist/upload-charm/index.js, src/services/charmcraft/charmcraft.test.ts, src/services/charmcraft/charmcraft.ts, upload-charm/README.md, upload-charm/action.yaml
As described in #98 
This PR aims to address a limitation of the upload-charm action, where it enforces a charm's OCI image to come from an external source.
Some projects include a charm folder within their project essentially keeping the application and the charm together. In order to use this action, such projects would need to first upload their image to a container registry and then use the provided action to pull from that registry.
The following change adds a config option called pull-image that, when set to false, will skip the docker pull step when uploading charm resources. This is useful in cases where the image is already present locally. An example of these changes in use can be seen [here](https://github.com/canonical/pga/actions/runs/5112992089/workflow). If the config is …
=> Add pull image option

.github/workflows/integrate.yaml, channel/action.yaml, check-libraries/action.yaml, release-charm/action.yaml, release-libraries/action.yaml, upload-bundle/action.yaml, upload-charm/action.yaml
This PR does two things:
- Bumps nodejs to the latest major LTS version (20)
- Adds a test to ensure that the build process succeeds
=> ci: run npm build during CI to ensure no failures

dist/channel/index.js, dist/check-libraries/index.js, dist/release-charm/index.js, dist/release-libraries/index.js, dist/upload-bundle/index.js, dist/upload-charm/index.js, src/services/charmcraft/charmcraft.ts
Charmcraft now supports charms that do not have `metadata.yaml` and these actions fail when run against these style charms.  
Example:
* https://github.com/canonical/k8s-operator/actions/runs/7791969417/job/21249115845
Fortunately, the metadata can be loaded out of `charmcraft.yaml` with the same structure for the most part
=> read metadata from charmcraft.yaml

dist/channel/index.js, dist/check-libraries/index.js, dist/release-charm/index.js, dist/release-libraries/index.js, dist/upload-bundle/index.js, dist/upload-charm/index.js, src/actions/upload-charm/upload-charm.test.ts, src/actions/upload-charm/upload-charm.ts, src/services/charmcraft/charmcraft.ts
In cases where `charmcraft pack` produces multiple charm files, this change enables the `upload-charm` action to upload and release them all, instead of just one of them.
Closes #106
=> Support uploading multiple charm files

README.md, dump-logs/README.md, dump-logs/action.yml
This PR adds a general purpose log dump action.
Unlike [canonical/charm-logdump-action](https://github.com/canonical/charm-logdump-action), this action does not make any assumption on (or requires an input for) the model name.
This is particularly useful for end-to-end tests where multiple controllers are bootstrapped. [Example](https://github.com/canonical/cos-lite-bundle/blob/0bd04b8d30ded073592554daca3b74f2c3bb0ffe/.github/workflows/ci.yaml#L101).
=> Add "dump-logs" action

dist/upload-charm/index.js, src/actions/upload-charm/upload-charm.ts, upload-charm/README.md, upload-charm/action.yaml
The `upload-charm` action cannot be used to upload temporary Charmhub releases (e.g., publish a charm to `latest/edge/temp-123`), because it automatically creates a GitHub tag (and release) whenever it's called; this obviously doesn't suit temporary releases.
Make the GitHub tagging process optional, by adding an extra (optional) input to the action.
(p.s. the unrelated edits are from the pre-commit hook running `prettier`)
=> make github tag in upload-charm optional

dist/channel/index.js, dist/check-libraries/index.js, dist/release-charm/index.js, dist/release-libraries/index.js, dist/upload-bundle/index.js, dist/upload-charm/index.js, package-lock.json, release-libraries/action.yaml, src/services/charmcraft/charmcraft.test.ts, src/services/charmcraft/charmcraft.ts
https://github.com/canonical/charming-actions/issues/86
Since `charmcraft publish-lib` exits with code 0 when publishing a library fails due to a higher than expected lib version, we are showing green builds in our CI when calling release-libraries action
- Inspect stdout and fail `publish-lib` if the error is encountered
- Update a npm module that had security vulnerabilities by running `npm audit fix`
=> Fail release-libraries action if the lib has libpatch greater than expected version

promote-charm/action.yaml
The `promote-charm` action entrypoint is incorrectly pointing to the `release-charm` action. This PR fixes it.
=> fix: promote-charm action entrypoint

dist/channel/index.js, dist/check-libraries/index.js, dist/promote-charm/index.js, dist/release-charm/index.js, dist/release-libraries/index.js, dist/upload-bundle/index.js, dist/upload-charm/index.js, src/actions/promote-charm/promote-charm.ts, src/actions/release-charm/release-charm.ts, src/actions/release-libraries/release-libraries.ts, src/services/charmcraft/charmcraft.test.ts, src/services/charmcraft/charmcraft.ts, src/types.ts
Charmcraft now supports extensions (https://discourse.charmhub.io/t/manage-extensions/13788), similar to Snapcraft extensions. These are built-in Python modules that can modify the contents of `charmcraft.yaml`, reducing boilerplate for charms that share common functionalities. Consequently, extensions can alter certain charm metadata, such as resources.
In the pull request, update the charming actions to apply extensions when necessary before getting charm metadata.
=> Support charms using charmcraft extensions

dist/channel/index.js, dist/check-libraries/index.js, dist/promote-charm/index.js, dist/release-charm/index.js, dist/release-libraries/index.js, dist/upload-bundle/index.js, dist/upload-charm/index.js, src/services/charmcraft/charmcraft.test.ts, src/services/charmcraft/charmcraft.ts, upload-charm/README.md
Use resource revision number returned by upload-resource command when uploading a charm with resources. This replaces the previous behaviour when the action was listing resources and was using the latest available.
The issue below documents why we need this change and why this change works. In short, the root cause is that Charmhub changed its behavior at some point and running `charmcraft upload-resource` does **not** create a new resource revision, breaking essentially the action which previously ran `charmcraft upload-resource` followed by `charmcraft  resource-revisions` and was attaching the latest available to the charm.
Here's an [example run](https://github.com/canonical/envoy-operator/actions/runs/9870973910/job/27257881279?pr=115#step:5:145) using the action from the PR's …
=> fix(upload-charm): Use resource revision from upload-resource command

dist/channel/index.js, dist/check-libraries/index.js, dist/promote-charm/index.js, dist/release-charm/index.js, dist/release-libraries/index.js, dist/upload-bundle/index.js, dist/upload-charm/index.js, src/services/bundle/bundle.ts
Closes #23 and #150.
This PR updates the `upload-bundle` action to decouple from the `juju-bundle` executable, found [here](https://github.com/canonical/juju-bundle). 
Essentially, the action now calls `charmcraft pack` on the bundle.yaml file's directory, captures the output to get the filename of the `.zip` bundle file, and then calls `charmcraft upload` for the appropriate channel and using the credentials in `$CHARMCRAFT_AUTH`.
Note that for some reason, all the output in the `charmcraft pack` executable is always on stderr, and not on stdout.
Here is an [example run](https://github.com/canonical/bundle-kubeflow/actions/runs/10578537130) using the action here.
=> fix(upload-bundle): Implement the same functionality without using `juju-bundle`

dump-logs/README.md
Update README.md to provide a more accurate example. Using without a tag results in the following error
```
the `uses' attribute must be a path, a Docker image, or owner/repo@ref
```
which can be a pain to debug, since the error doesn't indicate which part of the workflow it comes from (see example below)
```
---> "./.github/workflows/terraform-apply.yaml" (source branch with sha:4d31459a9d9ded130eceb2c50d3cc72a634cbbe5)
: the `uses' attribute must be a path, a Docker image, or owner/repo@ref
```
=> Update dump-logs README.md

dist/upload-charm/index.js, src/actions/upload-charm/upload-charm.test.ts, src/actions/upload-charm/upload-charm.ts, upload-charm/README.md, upload-charm/action.yaml
Support multiple pre-built charm paths in the `upload-charm` action.
Some charmcraft files could generate multiple charm files. This pull request modifies the `built-charm-path` property to support multiple charm files separated by commas while keeping the compatibility with a single path.
---
- Failing `upload-charms` job: https://github.com/canonical/k8s-operator/actions/runs/13021862096/job/36324029496
=> feat: support multiple built-charm-path

dist/channel/index.js, dist/check-libraries/index.js, dist/promote-charm/index.js, dist/release-charm/index.js, dist/release-libraries/index.js, dist/upload-bundle/index.js, dist/upload-charm/index.js, promote-charm/README.md, src/actions/promote-charm/promote-charm.ts, src/services/charmcraft/charmcraft.ts
Some old projects doesn't have all channels open and the current implementation is too strict  about this by throwing errors. #153 did this for older charms that used to have the `all` architecture, but this issue also happens for other scenarios. E.g:
- Charm ubuntu 16.04 (riscv64) has the channel latest/edge closed for prometheus-libvirt-exporter, but for some reason it has open for the stable:
```
ubuntu 16.04 (riscv64)  stable     7                  7           -
candidate  ↑                  ↑           ↑
beta       ↑                  ↑           ↑
edge       ↑                  ↑           ↑
```
This change filters only the base-arch combinations that have the target track/channel open, so it doesn't block all the releases.
=> Ignore bases that doesn't have a target channel open
